DemoScore/Controllers/ViewGameUserController.cs
using DemoScore.Models;
using DemoScore.Models.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SCORM1.Models.MainGame;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoScore.Controllers
{
    public class ViewGameUserController : Controller
    {
        protected ApplicationDbContext ApplicationDbContext { get; set; }
        protected UserManager<ApplicationUser> UserManager { get; set; }
        public ViewGameUserController()
        {
            this.ApplicationDbContext = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
        }

        public ApplicationUser GetActualUserId()
        {
            var userId = User.Identity.GetUserId();
            var user = UserManager.FindById(userId);
            return user;
        }
        [Authorize]
        public ActionResult TermsGame()
        {
            int CompanyUser = (int)GetActualUserId().CompanyId;
            var terms = ApplicationDbContext.MG_SettingMps.Where(x => x.Company_Id == CompanyUser).FirstOrDefault();
            if (GetActualUserId().TermsandConditions == Terms_and_Conditions.No)
            {
                UserGame model = new UserGame { };
                model.FileTerms = terms.Sett_Instruction;
                return PartialView("_TermsGame", model);
            }
            else
            {
                return RedirectToAction("Preview", "ViewGameuser", new { Id = terms.Sett_Id });
            }

        }
        [Authorize]
        public ActionResult Validateterms(UserGame model)
        {
            if (model.termsandGame == true)
            {
                int CompanyUser = (int)GetActualUserId().CompanyId;
                var id = GetActualUserId().Id;
                ApplicationUser user = ApplicationDbContext.Users.Find(id);
                user.TermsandConditions = Terms_and_Conditions.Si;
                ApplicationDbContext.SaveChanges();
                var terms = ApplicationDbContext.MG_SettingMps.Where(x => x.Company_Id == CompanyUser).FirstOrDefault();
                return RedirectToAction("Preview", "ViewGameuser", new { Id = terms.Sett_Id });
            }
            else
            {
                TempData["Info"] = "Para ingresar al contenido debe aceptar los terminos primero";
                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize]
        public ActionResult Preview(int Id)
        {
            var setting = ApplicationDbContext.MG_SettingMps.Find(Id);
            UserPreviw model = new UserPreviw
            {
                setting = setting,
                Sett_Id = setting.Sett_Id
            };
            return PartialView("_Preview", model);
        }

        [Authorize]
        public ActionResult Instructions(int Id)
        {
            var setting = ApplicationDbContext.MG_SettingMps.Find(Id);
            setting.MG_MultipleChoice = ApplicationDbContext.MG_MultipleChoices.Where(x => x.Nivel_Id == 1 && x.Sett_Id == Id).ToList();
            int cont = 0;
            var nivelattemp = 1;
            var useractual = ApplicationDbContext.Users.Find(GetActualUserId().Id);
            var countattempnivel = ApplicationDbContext.MG_AnswerUsers.Where(x => x.User_Id == useractual.Id && x.MG_AnswerMultipleChoice.MG_MultipleChoice.Nivel_Id == nivelattemp).Count();
            var counquestionnivel = ApplicationDbContext.MG_MultipleChoices.Where(x => x.Nivel_Id == nivelattemp && x.Sett_Id == Id).Count();
            var temp = ApplicationDbContext.MG_AnswerUsers.Where(x => x.User_Id == useractual.Id).OrderByDescending(x => x.AnUs_Id).ToList();
            var b = temp.FirstOrDefault();
            if (temp.Count != 0)
            {
                nivelattemp = b.MG_AnswerMultipleChoice.MG_MultipleChoice.Nivel_Id;
            }
            var attempts = ApplicationDbContext.MG_AnswerUsers.Where(x => x.User_Id == useractual.Id && x.MG_AnswerMultipleChoice.MG_MultipleChoice.Nivel_Id == nivelattemp).OrderByDescending(x => x.AnUs_Id).ToList();
            var a = attempts.GroupBy(x => x.Attemps).ToList();
            int attemptsUser = ApplicationDbContext.MG_AnswerUsers.Where(x => x.User_Id == useractual.Id && x.MG_AnswerMultipleChoice.MG_MultipleChoice.Nivel_Id == nivelattemp).GroupBy(x => x.Attemps).Count();
            if (attempts.Count != 0)
            {

                // numero de preguntas de la empresa en ese nivel
                counquestionnivel = ApplicationDbContext.MG_MultipleChoices.Where(x => x.Nivel_Id == nivelattemp && x.Sett_Id == Id).Count();
                //counquestionnivel = 100;
                // numero de preguntas respondidas por el usuario en ese nivel
                countattempnivel = ApplicationDbContext.MG_AnswerUsers.Where(x => x.User_Id == useractual.Id && x.MG_AnswerMultipleChoice.MG_MultipleChoice.Nivel_Id == nivelattemp).Count();
                if (countattempnivel >= counquestionnivel)
                {

                    if (nivelattemp < 3)
                    {
                        TempData["ultimo"] = "¡Felicidades has pasado el nivel sigue participando hasta el último nivel!";
                        nivelattemp = nivelattemp + 1;
                        countattempnivel = 0;
                    }
                    else
                    {
                        TempData["ultimo"] = "¡Felicidades!";
                        TempData["ultimo1"] = "Has completado el diagnóstico de conocimiento, tus resultados serán enviados directamente a tu correo en los próximos días, ya puedes volver a la comunidad.";
                    }
                }

                setting.MG_MultipleChoice = ApplicationDbContext.MG_MultipleChoices.Where(x => x.Nivel_Id == nivelattemp && x.Sett_Id == Id).ToList();
                //setting.MG_MultipleChoice=mg_setting;


                int att = ApplicationDbContext.MG_AnswerUsers.Where(x => x.Attemps == b.Attemps && x.User_Id == useractual.Id && x.MG_AnswerMultipleChoice.MG_MultipleChoice.Nivel_Id == nivelattemp).Count();
                cont = att + 1;
                if (att == counquestionnivel)
                {
                    if (TempData["ultimo"] == null)
                    {
                        if (b.Attemps == setting.Sett_Attemps)
                        {
                            TempData["ultimo"] = "Gracias por tu participación, tus resultados llegaran a tu correo electrónico en los proximos dias";
                            TempData["ultimo1"] = "¡Ya puedes cerrar tu sesión!";
                        }
                        else
                        {
                            TempData["ultimo"] = "¡Felicidades has pasado el nivel sigue participando hasta el último nivel!";
                        }

                        if (attemptsUser == setting.Sett_Attemps)
                        {
                            cont = 0;
                        }
                        else
                        {
                            cont = 1;
                        }
                    }
                }
            }

            else
            {
                cont = 1;
            }

            UserPreviw model1 = new UserPreviw
            {
                setting = setting,
                Sett_Id = setting.Sett_Id,
                Company_Id = setting.Company_Id,
                contador = countattempnivel,
                User_Id = useractual.Id,
                attemptUser = nivelattemp,
                countquestion = counquestionnivel,
                initial = 0
            };
            string result = string.Empty;
            byte[] encryted = System.Text.Encoding.Unicode.GetBytes(User.Identity.Name);
            result = Convert.ToBase64String(encryted);
            ViewData["usuario"] = result;
            return View(model1);
        }

        [Authorize]
        public ActionResult Question(int? id)
        {
            //int level = 0;            
            var useractual = ApplicationDbContext.Users.Find(GetActualUserId().Id);
            var company = ApplicationDbContext.Companies
                .Join(ApplicationDbContext.Categorias,
                        c => c.CompanyId,
                        cat => cat.Company_Id,
                        (c, cat) => new { c, cat })
                .Join(ApplicationDbContext.MG_MultipleChoices,
                        mch => mch.cat.Cate_ID,
                        mc => mc.Cate_Id,
                        (mch, mc) => new { mch, mc })
                .Join(ApplicationDbContext.Users,
                        u => u.mch.c.CompanyId,
                        com => com.CompanyId,
                        (u, com) => new { u, com })
                        .Where(us => us.com.Id == useractual.Id).FirstOrDefault();
            var settid = ApplicationDbContext.MG_SettingMps.Where(x => x.Company_Id == useractual.CompanyId).FirstOrDefault().Sett_Id;
            var nivelattemp = 1;
            var temp = ApplicationDbContext.MG_AnswerUsers.Where(x => x.User_Id == useractual.Id).OrderByDescending(x => x.AnUs_Id).ToList();
            var b2 = temp.FirstOrDefault();
            if (temp.Count != 0)
            {
                nivelattemp = b2.MG_AnswerMultipleChoice.MG_MultipleChoice.Nivel_Id;
            }
            // numero de preguntas de la compañia (empresa)
            var countquestioncompany = ApplicationDbContext.MG_MultipleChoices.Where(x => x.Sett_Id == company.u.mc.Sett_Id).Count();
            // numero de respuestas guardadas por el usuario
            var countanswerquestion = ApplicationDbContext.MG_AnswerUsers.Where(x => x.User_Id == useractual.Id).Count();
            if( countquestioncompany != countanswerquestion)
            {

            

DemoScore/Views/ViewGameUser/Preview.cshtml
@using DemoScore.Models.ViewModel;
@model UserPreviw
<body onload="setInterval('contador()',700)" style="background: url(../../ResourceGame/background-loading.jpg);
        background-size: cover;
        background-position: center center;
        background-repeat: no-repeat;
        background-attachment: fixed;">
    <br /><br /><br /><br /><br /><br />
    <div class="jumbotron3">
        <div class="col-md-12">
            <img src="~/Content/Imagenes/LOGO DCO-15.png" width="800px;" height="240px;"  />
            <br /><br /><br />
        </div>
        <div class="col-md-12">
            <br /><br /><br />
            @*<audio src="~/ResourceGame/@Model.setting.Sett_Audio3" autoplay loop></audio>*@
        </div>
        <br /><br /><br />
    </div>
</body>
<script type="text/javascript">

var num=5;
function contador() {
  num--;
  if (num == 0) location = '@Url.Action("Instructions", "ViewGameUser", new { id = Model.Sett_Id })';
  document.getElementById('seg').innerHTML=num;
}
</script>

DemoScore/Views/ViewGameUser/Question.cshtml
@using DemoScore.Models.ViewModel;
@model QuestionSelect
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/Scripts/Chart.js")
@Styles.Render("~/Content/style1.css")
@if (TempData["Info"] != null)
{
    @section Scripts {
        <script type="text/JavaScript">
            $(document).ready(function () {
                $("#DeleteInfo").modal();
            });
        </script>
    }}
<div id="DeleteInfo" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <h1 style="color:red"> @TempData["Info"]</h1>
                <br />


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<body style="background:url(../ImgTemplate/@Model.setting.MG_Template.Plant_Img_Questions); background-size: cover;background-position: center center;background-repeat: no-repeat;background-attachment: fixed;">
    <br /><br /><br />
    @using (Html.BeginForm("AnswerQuestions", "ViewGameUser", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
    {
        if (Model.setting.Sett_Audio4 != null)
        {
            <!--<audio src="~/ResourceGame/@Model.setting.Sett_Audio4" autoplay loop></audio>-->
        }

        for (int i = 0; i < Model.listquestionsselect.Count; i++)
        {
            <div class="preguntas col-md-12" align="center">
                <div style="background:url('../ImgTemplate/CUADROPREGUNTA(3).png');background-repeat: no-repeat; width:1080px;height:440px;padding:10px;">
                    @if (@Model.listquestionsselect[i].MuCh_Description != null)
                    {
                        <br /><br /><br /><br /><br /><br/>
                        <div class="Contexto_Preg">
                            <div style="text-align:center">
                                <h1 style="text-align:center;"><strong>@Model.listquestionsselect[i].Contexto.Contex_Compet</strong></h1><br />
                            </div>
                            @if (Model.listquestionsselect[i].Contexto.Contex_Desc != null)
                            {
                                <h1>@Html.Raw(@Model.listquestionsselect[i].Contexto.Contex_Desc)</h1><br />
                            }
                            @if (Model.listquestionsselect[i].Contexto.Contex_Autor != null)
                            {
                                <h1><strong>Tomado de: </strong>@Model.listquestionsselect[i].Contexto.Contex_Autor</h1>
                                <br />
                            }
                        </div>
                        <br />
                        <div class="row">
                            @*<div class="col-md-2">
                                <h1><strong>Pregunta: </strong></h1>
                            </div>*@
                            <div class="col-md-11" style="text-align:left; margin-left:2%; margin-top:-5%">
                                <h1>@Html.Raw(@Model.listquestionsselect[i].MuCh_Description)</h1>
                            </div>
                        </div>
                    }
                    else
                    {
                        <img src="~/Mg_Game_Image/@Model.listquestionsselect[i].MuCh_ImageQuestion" style="width:400px; height:210px" />
                    }
                </div>
            </div>
            <div class="col-md-12">
                <div class="jumbotron3">
                    <div class="col-md-12">
                        <br /><br /><br />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div>
                        <a class="Select" href="#" onclick="UpdateModule('@Model.listquestionsselect[i].listanswerM[0].AnMul_ID')" data-cname="@Model.listquestionsselect[i].listanswerM[0].AnMul_ID"><h1>A. @Model.listquestionsselect[i].listanswerM[0].AnMul_Description</h1></a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div>
                        <a class="Select" href="#" onclick="UpdateModule('@Model.listquestionsselect[i].listanswerM[1].AnMul_ID')" data-cname="@Model.listquestionsselect[i].listanswerM[1].AnMul_ID"><h1>B. @Model.listquestionsselect[i].listanswerM[1].AnMul_Description</h1></a>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="jumbotron3">
                    <div class="col-md-12">
                        <br />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div>
                        <a class="Select" href="#" onclick="UpdateModule('@Model.listquestionsselect[i].listanswerM[2].AnMul_ID')" data-cname="@Model.listquestionsselect[i].listanswerM[2].AnMul_ID"><h1>C. @Model.listquestionsselect[i].listanswerM[2].AnMul_Description</h1></a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div>
                        <a class="Select" href="#" onclick="UpdateModule('@Model.listquestionsselect[i].listanswerM[3].AnMul_ID')" data-cname="@Model.listquestionsselect[i].listanswerM[3].AnMul_ID"><h1>D. @Model.listquestionsselect[i].listanswerM[3].AnMul_Description</h1></a>
                    </div>
                </div>
            </div>
        }
        <div class="jumbotron3">
            <div class="col-md-12">
                <br />
            </div>
            <div class="col-md-12">
            </div>
            <div class="col-md-12">

            </div>
        </div>
    }
</body>

<script>
    function UpdateModule(AnMul_ID)
{
      var a = AnMul_ID;
      window.location.href = '@Url.Action("AnswerQuestions", "ViewGameUser", new { id ="ID"})'.replace("ID", a);
    }
</script>

DemoScore/Views/ViewGameUser/TermsGame.cshtml
@using DemoScore.Models.ViewModel
@model   UserGame
@if (TempData["Info"] != null)
{
    @section Scripts {
        <script type="text/JavaScript">
    $(document).ready(function () {
        $("#Inform").modal();
    });
        </script>
    }}
<div id="Inform" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                @TempData["Info"]
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<div class="panel-primary">

    <br /><br /><br /><br /><br />
    <h1 class="title"> Instruciones Diagnóstico del Mapa de Conocimiento Organizacional</h1>
    <embed src="~/TermsandConditions/@Model.FileTerms" width="800" height="375">
    @using (Html.BeginForm("Validateterms", "ViewGameUser", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <br /><br />
            @*<div class="col-md-12">
                <div class="col-md-12">
                    <h1 class="title">Tutorial Diagnóstico del Mapa de Conocimiento Organizacional</h1>
                    <video controls="controls" width="800" height="500">
                        <source src="https://www.aprendeyavanza2.com.co/SaludVida/Recursos/video_introduccion%20_SCORE.mp4" type="video/mp4" />
                    </video>
                </div>
            </div><br />*@
            <br /><br />
            <div class="col-md-offset-2 col-md-8">
                <br /><br /><br />
                @Html.CheckBoxFor(m => m.termsandGame, htmlAttributes: new { @class = "", @style = "width: 50px;height: 30px; " })
                @Html.LabelFor(m => m.termsandGame)
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-8">
                    <br /><br />
                    <center><button class="btn btn-primary" name="singin" type="submit">Continuar</button></center>
                </div>
            </div>
    }
</div>

DemoScore/Views/ViewGameUser/_Preview.cshtml
@using DemoScore.Models.ViewModel;
@model UserPreviw
<body onload="setInterval('contador()',700)" style="background:url(./ResourceGame/FondoInicio.jpg); background-size: cover;background-position: center center;background-repeat: no-repeat;background-attachment: fixed;">
    <br /><br /><br /><br /><br /><br />
    <div class="jumbotron3">
        <div class="col-md-12">
            <!--<img src="~/Content/Imagenes/LOGO DCO-15.png" width="800px;" height="240px;" />-->
            <br /><br /><br />
            <br /><br /><br />
            <br /><br /><br />
            <br /><br /><br />
            <br /><br /><br />
            <br /><br /><br />
            <br /><br /><br />
        </div>
        <div class="col-md-12">
            <br /><br /><br />
            <!--<audio src="~/ResourceGame/@Model.setting.Sett_Audio3" autoplay loop></audio>-->
        </div>
        <br /><br /><br />
    </div>
</body>
<script type="text/javascript">

var num=5;
function contador() {
  num--;
  if (num == 0) location = '@Url.Action("Instructions", "ViewGameUser", new { id = Model.Sett_Id })';
  document.getElementById('seg').innerHTML=num;
}
</script>

DemoScore/Views/ViewGameUser/_TermsGame.cshtml
@using DemoScore.Models.ViewModel
@model   UserGame
@if (TempData["Info"] != null)
{
    @section Scripts {
        <script type="text/JavaScript">
    $(document).ready(function () {
        $("#Inform").modal();
    });
        </script>
    }}
<div id="Inform" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                @TempData["Info"]
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<div class="panel-primary">

    <br /><br /><br /><br /><br />
    <h1 class="title"> </h1>
    <embed src="~/TermsandConditions/@Model.FileTerms" width="800" height="375">
    @using (Html.BeginForm("Validateterms", "ViewGameUser", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <br /><br />
        @*<div class="col-md-12">
            <div class="col-md-12">
                <h1 class="title">Tutorial Diagnóstico del Mapa de Conocimiento Organizacional</h1>
                <video controls="controls" width="800" height="500">
                    <source src="https://www.aprendeyavanza2.com.co/SaludVida/Recursos/video_introduccion%20_SCORE.mp4" type="video/mp4" />
                </video>
            </div>
        </div><br />
            <br /><br />*@
            <div class="col-md-offset-2 col-md-8" style="color:black">
                <br /><br /><br />
                @Html.CheckBoxFor(m => m.termsandGame, htmlAttributes: new { @class = "", @style = "width: 50px;height: 30px; " })
                @Html.LabelFor(m => m.termsandGame)
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-8">
                    <br /><br />
                    <center><button class="btn btn-primary" name="singin" type="submit">Continuar</button></center>
                </div>
            </div>
    }
</div>