DemoScore/Controllers/AdminGameController.cs
using DemoScore.Models;
using DemoScore.Models.Game;
using DemoScore.Models.ViewModel;
using Excel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SCORM1.Models.MainGame;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoScore.Controllers
{
    public class AdminGameController : Controller
    {
        protected ApplicationDbContext ApplicationDbContext { get; set; }
        protected UserManager<ApplicationUser> UserManager { get; set; }

        public AdminGameController()
        {
            this.ApplicationDbContext = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
        }

        public ApplicationUser GetActualUserId()
        {
            var userId = User.Identity.GetUserId();
            var user = UserManager.FindById(userId);
            return user;
        }


        public IEnumerable<SelectListItem> GetTemplate()
        {
            List<MG_Template> Templates = ApplicationDbContext.MG_Templates.ToList();
            IEnumerable<SelectListItem> Template = Templates.Select(x =>
           new SelectListItem
           {
               Value = x.Plant_Id.ToString(),
               Text = x.Plant_Color
           });
            return new SelectList(Template, "Value", "Text");
        }
        public IEnumerable<SelectListItem> GetAudios()
        {

            List<string> audios = new List<string>();
            audios.Add("Instrucciones.mp3");
            audios.Add("respuesta.mp3");
            audios.Add("inicio.mp3");
            audios.Add("pregunta.mp3");
            audios.Add("ganador.mp3");
            IEnumerable<SelectListItem> audio = audios.Select(x =>
           new SelectListItem
           {
               Value = x.ToString(),
               Text = x.ToString()
           });
            return new SelectList(audio, "Value", "Text");
        }
        public IEnumerable<SelectListItem> GetCategory(int com)
        {
            List<Categoria> category = ApplicationDbContext.Categorias.Where(x => x.Company_Id == com).ToList();
            IEnumerable<SelectListItem> Template = category.Select(x =>
           new SelectListItem
           {
               Value = x.Cate_ID.ToString(),
               Text = x.Cate_Description
           });
            return new SelectList(Template, "Value", "Text");
        }
        public IEnumerable<SelectListItem> GetSubcategory(int com)
        {

            List<SubCategoria> subcate = ApplicationDbContext.SubCategorias.Where(x => x.Company_Id == com).ToList();
            IEnumerable<SelectListItem> Template = subcate.Select(x =>
           new SelectListItem
           {
               Value = x.SubC_ID.ToString(),
               Text = x.SubC_Description
           });
            return new SelectList(Template, "Value", "Text");
        }
        public IEnumerable<SelectListItem> GetNivel()
        {
            List<Nivel> nivel = ApplicationDbContext.Nivels.ToList();
            IEnumerable<SelectListItem> Template = nivel.Select(x =>
           new SelectListItem
           {
               Value = x.Nivel_Id.ToString(),
               Text = x.Nivel_Name
           });
            return new SelectList(Template, "Value", "Text");
        }
        public IEnumerable<SelectListItem> GetContext( int com)
        {
            List<MG_Context> contexts = ApplicationDbContext.MG_Contexts.Where(x => x.Contex_Id == com).ToList();
            IEnumerable<SelectListItem> Template = contexts.Select(x =>
            new SelectListItem
            {
                Value = x.Contex_Id.ToString(),
                Text = x.Contex_Desc
            });
            return new SelectList(Template, "Value", "Text");
        }

        public ActionResult Companies()
        {
            List<Company> Companies = ApplicationDbContext.Companies.ToList();
            List<infocompany> listcompany = new List<infocompany>();
            if (Companies.Count != 0)
            {


                foreach (var item in Companies)
                {
                    int user = ApplicationDbContext.Users.Where(X => X.CompanyId == item.CompanyId).ToList().Count();
                    listcompany.Add(new infocompany
                    {
                        CompanyId = item.CompanyId,
                        CompanyName = item.CompanyName,
                        CompanyUser = user
                    });
                }
            }
            AdminGeneralViewModel model = new AdminGeneralViewModel
            {
                ListCompanies = listcompany
            };
            return View(model);
        }
        [Authorize]
        public ActionResult Setting(int id)
        {
            var company = ApplicationDbContext.Companies.Find(id);
            var setting = ApplicationDbContext.MG_SettingMps.Where(x => x.Company_Id == company.CompanyId).ToList();
            var a = "";
            if (setting.Count != 0)
            {
                a = setting.FirstOrDefault().Sett_Instruction;
            }
            else
            {
                var settings = ApplicationDbContext.MG_SettingMps.FirstOrDefault();
                a = settings.Sett_Instruction;
            }
            AdminGameSetting model = new AdminGameSetting
            {
                ListSetting = setting,
                Sett_Templates = GetTemplate(),
                Sett_Audios = GetAudios(),
                TermsGame = a,
                companyId = id
            };
            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult AddSetting(AdminGameSetting model)
        {
            var GetCompanyId = ApplicationDbContext.Companies.Find(model.companyId);
            if (ModelState.IsValid)
            {
                var template = ApplicationDbContext.MG_Templates.Find(model.Plan_Id);

                MG_SettingMp Setting = new MG_SettingMp
                {

                    Sett_InitialDate = model.Sett_InitialDate,
                    Sett_CloseDate = model.Sett_CloseDate,
                    MG_Template = template,
                    Company_Id = GetCompanyId.CompanyId,
                    Company = GetCompanyId,
                    Sett_Instruction = "20171017152016-administracion formacion - matriculas.pdf",
                    Sett_Audio1 = model.Sett_Audio1,
                    Sett_Audio2 = model.Sett_Audio2,
                    Sett_Audio3 = model.Sett_Audio3,
                    Sett_Audio4 = model.Sett_Audio4,
                    Sett_Audio5 = model.Sett_Audio5,
                    Sett_Attemps = 3
                };
                ApplicationDbContext.MG_SettingMps.Add(Setting);
                ApplicationDbContext.SaveChanges();
                return RedirectToAction("Setting", new { id = model.companyId });
            }
            TempData["AddMessageError"] = "Se debe Crear una plantilla primero";
            return View("Setting", model);
        }

        [Authorize]
        public ActionResult DeleteSetting(int id)
        {
            MG_SettingMp deletedSetting = ApplicationDbContext.MG_SettingMps.Find(id);
            int com = deletedSetting.Company_Id;
            if (deletedSetting.MG_MultipleChoice.Count != 0)
            {
                TempData["Info"] = "No se puede eliminar la configuración del juego debido a que, se encuentra información asociada";
            }
            else
            {
                TempData["Info"] = "Configuración eliminada con éxito";
                ApplicationDbContext.MG_SettingMps.Remove(deletedSetting);
                ApplicationDbContext.SaveChanges();
            }

            return RedirectToAction("Setting", new { id = com });
        }

        [Authorize]
        public ActionResult UpdateSetting(int id)
        {

            MG_SettingMp updatedSetting = ApplicationDbContext.MG_SettingMps.Find(id);
            TempData["UpdateSetting"] = "Modificada con exito";
            AdminGameSetting model = new AdminGameSetting
            {

                ListSetting = ApplicationDbContext.MG_SettingMps.Where(c => c.Company_Id == updatedSetting.Company_Id).ToList(),
                Sett_Id = updatedSetting.Sett_Id,
                Sett_InitialDate = updatedSetting.Sett_InitialDate,
                Sett_CloseDate = updatedSetting.Sett_CloseDate,
                Plan_Id = updatedSetting.Plan_Id,
                Sett_Audio1 = updatedSetting.Sett_Audio1,
                Sett_Audio2 = updatedSetting.Sett_Audio2,
                Sett_Audio3 = updatedSetting.Sett_Audio3,
                Sett_Audio4 = updatedSetting.Sett_Audio4,
                Sett_Audio5 = updatedSetting.Sett_Audio5,
                Sett_Templates = GetTemplate(),
                Sett_Audios = GetAudios()
            };
            return View("Setting", model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult UpdateSetting(AdminGameSetting model)
        {
            MG_SettingMp updatedSetting = ApplicationDbContext.MG_SettingMps.Find(model.Sett_Id);
            if (ModelState.IsValid)
            {

                TempData["Info"] = "La configuración se ha modificado con éxito.";
                updatedSetting.Sett_InitialDate = model.Sett_InitialDate;
                updatedSetting.Sett_CloseDate = model.Sett_CloseDate;
                updatedSetting.Plan_Id = model.Plan_Id;
                updatedSetting.MG_Template = ApplicationDbContext.MG_Templates.Find(model.Plan_Id);
                updatedSetting.Sett_Audio1 = model.Sett_Audio1;
                updatedSetting.Sett_Audio2 = model.Sett_Audio2;
                updatedSetting.Sett_Audio3 = model.Sett_Audio3;
                updatedSetting.Sett_Audio4 = model.Sett_Audio4;

DemoScore/Controllers/ViewGameController.cs
using DemoScore.Models;
using DemoScore.Models.Game;
using DemoScore.Models.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoScore.Controllers
{
    public class ViewGameController : Controller
    {
        protected ApplicationDbContext ApplicationDbContext { get; set; }
        protected UserManager<ApplicationUser> UserManager { get; set; }

        public ViewGameController()
        {
            this.ApplicationDbContext = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
        }

        public ApplicationUser GetActualUserId()
        {
            var userId = User.Identity.GetUserId();
            var user = UserManager.FindById(userId);
            return user;
        }

        [Authorize]
        public ActionResult Preview(int Id)
        {
            var setting = ApplicationDbContext.MG_SettingMps.Find(Id);
            AdminPreviw model = new AdminPreviw
            {
                setting = setting,
                Sett_Id = setting.Sett_Id
            };
            return View(model);
        }

        [Authorize]
        public ActionResult Instructions(int Id)
        {
            var setting = ApplicationDbContext.MG_SettingMps.Find(Id);
            List<MultipleChoiceDificil> ListQuestionsdificil = new List<MultipleChoiceDificil>();
            if (setting.MG_MultipleChoice.Count> 44)
            {
                foreach (var item in setting.MG_MultipleChoice)
                {
                    ListQuestionsdificil.Add(new MultipleChoiceDificil
                    {
                        Sett_Id = item.Sett_Id,
                        MuCh_ID = item.MuCh_ID,
                        MuCh_Description = item.MuCh_Description,
                        MuCh_ImageQuestion = item.MuCh_ImageQuestion,
                        listanswerM = item.MG_AnswerMultipleChoice.ToList()
                    });
                }
               
            }
            else
            {
                TempData["Info"] = "Por favor complete el banco de pregunta, el cual debe corresponder a 45 preguntas";
            }
           
            var rnd = new Random();
            //var randomlistdificil = ListQuestionsdificil.OrderBy(x => rnd.Next()).ToList();
            var Newlistdificil = ListQuestionsdificil;
            List<MultipleChoiceDificil> ListFinaldificil = new List<MultipleChoiceDificil>(Newlistdificil);
            AdminPreviw model = new AdminPreviw
            {
                setting = setting,
                Sett_Id = setting.Sett_Id,
                listquestionsDificil = ListFinaldificil
            };
            
            return View(model);
        }

        [Authorize]
        public ActionResult Question(int id, int contador)
        {
            var question = ApplicationDbContext.MG_MultipleChoices.Find(id);
            List<MultipleChoiceselect> listselect = new List<MultipleChoiceselect>();
            if (question != null)
            {
                MG_Context contexto = ApplicationDbContext.MG_Contexts.Find(question.Contex_Id);
                listselect.Add(new MultipleChoiceselect
                {
                    MuCh_ID = question.MuCh_ID,
                    MuCh_Description = question.MuCh_Description,
                    MuCh_ImageQuestion = question.MuCh_ImageQuestion,
                    Sett_Id = question.Sett_Id,
                    listanswerM = question.MG_AnswerMultipleChoice.ToList(),
                    Contexto = contexto
                });
                QuestionSelect model = new QuestionSelect
                {
                    Sett_Id = question.Sett_Id,
                    contador = contador,
                    listquestionsselect = listselect,
                    setting = question.MG_SettingMp
                };
                return View(model);
            }
            return RedirectToAction("Instructions", new { Id = question.Sett_Id });
        }


    }
}

DemoScore/Views/ViewGame/Instructions.cshtml
@using DemoScore.Models.ViewModel;
@model AdminPreviw
@Scripts.Render("~/bundles/jqueryval")
@if (TempData["Info"] != null)
{
    @section Scripts {
        <script type="text/JavaScript">
            $(document).ready(function () {
                $("#DeleteInfo").modal();
            });
        </script>
    }}
@if (Model.setting.Sett_Audio1 != null)
{
    @*<audio src="~/ResourceGame/@Model.setting.Sett_Audio1" autoplay loop></audio>*@
}
<div id="DeleteInfo" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <h1 style="color:red"> @TempData["Info"]</h1>
                <br />
      

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<body style="background:url(../../ImgTemplate/@Model.setting.MG_Template.Plant_Img_instructions); background-size: cover;background-position: center center;background-repeat: no-repeat;background-attachment: fixed;">
    <br /><br /><br /><br /><br /><br />
    <div class="row fecha">
        <div class="btn-group btn-breadcrumb">
            <a href="@Url.Action("Index", "Home")" class="btn btn-info"><i class="glyphicon glyphicon-home"></i></a>
            <a href="@Url.Action("Setting", "AdminGame")" class="btn btn-info">Ajuste Juego</a>
            <a href="@Url.Action("MgQuestions", "AdminGame", new {id = Model.Sett_Id})" class="btn btn-info">Preguntas</a>
        </div>
    </div>
    <br />

    @if (Model.listquestionsDificil.Count > 44)
    {
        <div class="preguntas2 col-md-4" style="left:480px;">
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[0].MuCh_ID, contador=2})">
                    <img src="~/ResourceGame/Nivel1.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[1].MuCh_ID, contador=3})">
                    <img src="~/ResourceGame/2 (6).png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[2].MuCh_ID, contador=4})">
                    <img src="~/ResourceGame/Nivel3.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[3].MuCh_ID, contador=5})">
                    <img src="~/ResourceGame/4 (1).png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[4].MuCh_ID, contador=6})">
                    <img src="~/ResourceGame/5 (1).png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[5].MuCh_ID, contador=7})">
                    <img src="~/ResourceGame/Nivel6.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[6].MuCh_ID, contador=8})">
                    <img src="~/ResourceGame/Nivel7.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[7].MuCh_ID, contador=9})">
                    <img src="~/ResourceGame/Nivel8.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[8].MuCh_ID, contador=10})">
                    <img src="~/ResourceGame/Nivel9.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[9].MuCh_ID, contador=11})">
                    <img src="~/ResourceGame/Nivel10.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[10].MuCh_ID, contador=12})">
                    <img src="~/ResourceGame/Nivel11.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[11].MuCh_ID, contador=13})">
                    <img src="~/ResourceGame/Nivel12.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[12].MuCh_ID, contador=14})">
                    <img src="~/ResourceGame/Nivel13.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[13].MuCh_ID, contador=15})">
                    <img src="~/ResourceGame/Nivel14.png" class="img-responsive" />
                </a>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Question", "ViewGame", new {id = Model.listquestionsDificil[14].MuCh_ID, contador=16})">
                    <img src="~/ResourceGame/Nivel15.png" class="img-responsive" />
                </a>
            </div>

        </div>
    }
    

    <div class="col-md-4">

    </div>
    <div class="col-md-4" style="left:100px;">

        <div class="col-md-12">
            <div class="col-md-12">
                <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
            </div>
            
        </div>
    </div>

</body>

<script>
    //method Delete User
    function ResteUserGame(Sett_Id) {
        if (confirm("Elimiar Datos del Juego (Perdera toda la información del juego sobre la participación de los usuaios. (NO se puede revertir))") == true) {
            var set = Sett_Id;
            window.location.href = ' @Url.Action("ResetGame", "ViewGame", new { Id = "ID" })'.replace("ID", set);
        }
    }


</script>

DemoScore/Views/ViewGame/Preview.cshtml
@using DemoScore.Models.ViewModel;
@model AdminPreviw



<body onload="setInterval('contador()',700)" style="background:url(../../ResourceGame/FondoInicio.jpg); background-size: cover;background-position: center center;background-repeat: no-repeat;background-attachment: fixed;">
    <br /><br /><br /><br /><br /><br />
    <div class="row fecha">
        <div class="btn-group btn-breadcrumb">
            <a href="@Url.Action("Index", "Home")" class="btn btn-info"><i class="glyphicon glyphicon-home"></i></a>
            <a href="@Url.Action("Setting", "AdminGame")" class="btn btn-info">Ajuste Juego</a>
            <a href="@Url.Action("MgQuestions", "AdminGame", new {id = Model.Sett_Id})" class="btn btn-info">Preguntas</a>
        </div>
    </div>
    <div class="jumbotron3">
        <div class="col-md-12">
            <img src="~/Content/Imagenes/LOGO DCO-15.png" width="800px;" height="240px;" />
            <br /><br /><br />
        </div>
        <div class="col-md-12">
            <br /><br /><br />
            @*<audio src="~/ResourceGame/@Model.setting.Sett_Audio3" autoplay loop></audio>*@
        </div>
        <br /><br /><br />
    </div>
</body>

<script type="text/javascript">

var num=6;
function contador() {
  num--;
  if (num == 0) location = '@Url.Action("Instructions", "ViewGame", new { id = Model.Sett_Id })';
  document.getElementById('seg').innerHTML=num;
}
</script>

DemoScore/Views/ViewGame/Question.cshtml
@using DemoScore.Models.ViewModel;
@model QuestionSelect
@Scripts.Render("~/bundles/jqueryval")
@if (TempData["Info"] != null)
{
    @section Scripts {
        <script type="text/JavaScript">
            $(document).ready(function () {
                $("#DeleteInfo").modal();
            });
        </script>
    }}

<div id="DeleteInfo" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <h1 style="color:red"> @TempData["Info"]</h1>
                <br />


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<body style="background:url(../../ImgTemplate/@Model.setting.MG_Template.Plant_Img_Questions); background-size: cover;background-position: center center;background-repeat: no-repeat;background-attachment: fixed;">
    <br /><br /><br /><br /><br /><br />
    @using (Html.BeginForm("Instructions", "ViewGame", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
    {
        <div class="row fecha">
            <div class="btn-group btn-breadcrumb">
                <a href="@Url.Action("Index", "Home")" class="btn btn-info"><i class="glyphicon glyphicon-home"></i></a>
                <a href="@Url.Action("Setting", "AdminGame")" class="btn btn-info">Ajuste Juego</a>
                <a href="@Url.Action("MgQuestions", "AdminGame", new { id = Model.Sett_Id })" class="btn btn-info">Preguntas</a>
            </div>
        </div>
        for (int i = 0; i < Model.listquestionsselect.Count; i++)
        {
            <div class="preguntas col-md-7" style="left:350px;">
                <div style="background:url('../../ImgTemplate/CUADROPREGUNTA(3).png');background-repeat: no-repeat; width:600px;height:230px;padding:10px;">
                    @if (@Model.listquestionsselect[i].MuCh_Description != null)
                    {
                        <br /><br /><br /><br /><br />
                        <h1> @Model.listquestionsselect[i].MuCh_Description</h1>
                    }
                    else
                    {
                        <img src="~/Mg_Game_Image/@Model.listquestionsselect[i].MuCh_ImageQuestion" style="width:400px; height:210px" />
                    }
                </div>
            </div>
            <div class="col-md-12">
                <div class="jumbotron3">
                    <div class="col-md-12">
                        <br /><br /><br /><br /><br />
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="pruebas">
                    <br />
                    <a class="Select" href="@Url.Action("Instructions", "ViewGame", new { Id = Model.Sett_Id })" onclick="UpdateModule('@Model.listquestionsselect[i].listanswerM[0].AnMul_ID')" data-cname="@Model.listquestionsselect[i].listanswerM[0].AnMul_ID"><h1>A. @Model.listquestionsselect[i].listanswerM[0].AnMul_Description</h1></a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="pruebas3">
                    <br />
                    <a class="Select" href="@Url.Action("Instructions", "ViewGame", new { Id = Model.Sett_Id })" onclick="UpdateModule('@Model.listquestionsselect[i].listanswerM[1].AnMul_ID')" data-cname="@Model.listquestionsselect[i].listanswerM[1].AnMul_ID"><h1>B. @Model.listquestionsselect[i].listanswerM[1].AnMul_Description</h1></a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="pruebas2">
                    <br />
                    <a class="Select" href="@Url.Action("Instructions", "ViewGame", new { Id = Model.Sett_Id })" onclick="UpdateModule('@Model.listquestionsselect[i].listanswerM[2].AnMul_ID')" data-cname="@Model.listquestionsselect[i].listanswerM[2].AnMul_ID"><h1>C. @Model.listquestionsselect[i].listanswerM[2].AnMul_Description</h1></a>
                </div>
            </div>
                <div class="col-md-6">
                    <div class="pruebas4">
                        <br />
                        <a class="Select" href="@Url.Action("Instructions", "ViewGame", new { Id = Model.Sett_Id })" onclick="UpdateModule('@Model.listquestionsselect[i].listanswerM[3].AnMul_ID')" data-cname="@Model.listquestionsselect[i].listanswerM[3].AnMul_ID"><h1>D. @Model.listquestionsselect[i].listanswerM[3].AnMul_Description</h1></a>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="jumbotron3">
                        <div class="col-md-12">
                            <br /><br /><br /><br /><br />
                        </div>
                    </div>
                </div>
        }
        <div class="jumbotron3">

            <div class="col-md-12">
                <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
            </div>
            <div class="col-md-12">

            </div>
            <div class="col-md-12">
                @*<audio src="~/ResourceGame/Quien_Quiere_ser_millonario_Cancin_Inicial_-vi9jLV63W8.mp3" autoplay loop></audio>*@
            </div>
        </div>
    }
</body>