DemoScore/Models/ViewModel/UserAndMassiveManagementViewModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoScore.Models.ViewModel
{
    public class UserAndMassiveManagementViewModel 
    {
        public IPagedList<ApplicationUser> UserOfCompany { get; set; }

        //Create User
        public string UserId { get; set; }
        public int CompanyId { get; set; }

        [Display(Name = "Nombre de usuario")]
        [Required(ErrorMessage = "Se Debe Contar con un Nick de Usuario")]
        public string UserName { get; set; }

        [Display(Name = "Nombres")]
        [Required(ErrorMessage = "Se Debe Contar con un Nombre")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Se Debe Contar con un Apellido")]
        [Display(Name = "Apellidos")]
        public string LastName { get; set; }

        [Display(Name = "Rol")]
        [Required(ErrorMessage = "Se Debe Contar con un Rol de Usuario")]
        public ROLES Role { get; set; }

        [Display(Name = "Documento")]
        public string Document { get; set; }

        [Display(Name = "Cargo")]
        public int? PositionId { get; set; }

        [Display(Name = "Area")]
        public int? AreaId { get; set; }

        [Display(Name = "Ciudad")]
        public int? CityId { get; set; }

        [Display(Name = "Ubicación")]
        public int? LocationId { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        public IEnumerable<SelectListItem> AreasOfTheCompany { get; set; }
        public IEnumerable<SelectListItem> PositionTheCompany { get; set; }
        public IEnumerable<SelectListItem> CityOfTheCompany { get; set; }
        public IEnumerable<SelectListItem> LocationOfTheCompany { get; set; }

        //Create the Areas
        [Display(Name = "Area")]
        public string AreaName { get; set; }

        //Create the Locations
        [Display(Name = "Ubicación")]
        public string LocationName { get; set; }

        //Create the Citys
        [Display(Name = "Ciudad")]
        public string CityName { get; set; }

        //Create the Positions
        [Display(Name = "Cargo")]
        public string PositionName { get; set; }
    }

    public class LogoUserMasive
    {
        public int companyId { get; set; }
        public DataTable data { get; set; }
    }
    public class LogoUserUpdate
    {
        public DataTable data { get; set; }
        public List<UserUpdate> usuarios_actualizados { get; set; }
        public List<UserNew> usuarios_nuevos { get; set; }
    }
    public class UserUpdate
    {
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string document { get; set; }
        public int codigo_area { get; set; }
        public string área { get; set; }
        public int codigo_ubicación { get; set; }
        public string ubicación { get; set; }
        public int codigo_cargo { get; set; }
        public string cargo { get; set; }
        public int codigo_ciudad { get; set; }
        public string ciudad { get; set; }

    }
    public class UserNew
    {
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string document { get; set; }
        public int codigo_area { get; set; }
        public string área { get; set; }
        public int codigo_ubicación { get; set; }
        public string ubicación { get; set; }
        public int codigo_cargo { get; set; }
        public string cargo { get; set; }
        public int codigo_ciudad { get; set; }
        public string ciudad { get; set; }

    }
}

DemoScore/Controllers/UserAndMassiveManagementController.cs
using DemoScore.Models;
using DemoScore.Models.Game;
using DemoScore.Models.ViewModel;
using Excel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace DemoScore.Controllers
{
    public class UserAndMassiveManagementController : Controller
    {
        protected ApplicationDbContext ApplicationDbContext { get; set; }
        protected UserManager<ApplicationUser> UserManager { get; set; }
        private ApplicationSignInManager _signInManager;
        public UserAndMassiveManagementController()
        {
            this.ApplicationDbContext = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));

        }
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        // GET: UserAndMassiveManagement

        public ActionResult Companies()
        {
            List<Company> Companies = ApplicationDbContext.Companies.ToList();
            List<infocompany> listcompany = new List<infocompany>();
            if (Companies.Count != 0)
            {


                foreach (var item in Companies)
                {
                    int user = ApplicationDbContext.Users.Where(X => X.CompanyId == item.CompanyId).ToList().Count();
                    listcompany.Add(new infocompany
                    {
                        CompanyId = item.CompanyId,
                        CompanyName = item.CompanyName,
                        CompanyUser = user
                    });
                }
            }
            AdminGeneralViewModel model = new AdminGeneralViewModel
            {
                ListCompanies = listcompany
            };
            return View(model);
        }
        public ActionResult ManagementUser(int id,int? page)
        {
            var companyId = ApplicationDbContext.Companies.Find(id);
            IPagedList<ApplicationUser> ListOfUser = ApplicationDbContext.Users.OrderBy(x => x.UserName).Where(x => x.CompanyId == companyId.CompanyId).ToList().ToPagedList(page ?? 1, 6);


            UserAndMassiveManagementViewModel model = new UserAndMassiveManagementViewModel
            {
                UserOfCompany = ListOfUser,
                AreasOfTheCompany = GetArea(companyId.CompanyId),
                CityOfTheCompany = GetCityOfTheCompany(),
                LocationOfTheCompany = GetLocationOfTheCompany(companyId.CompanyId),
                PositionTheCompany = GetPosition(companyId.CompanyId),
                CompanyId=id       
            };           
            return View(model);
        }
        

        public ActionResult SearchUserManager(UserAndMassiveManagementViewModel model, int? page)
        {
            var companyId = model.CompanyId;
            if (string.IsNullOrEmpty(model.UserId) || string.IsNullOrWhiteSpace(model.UserId))
            {
              
                return RedirectToAction("ManagementUser", new {id=model.CompanyId });
            }
            else
            {
                IPagedList<ApplicationUser> ListOfUser = ApplicationDbContext.Users.OrderBy(x => x.UserName).Where(x => x.CompanyId == companyId && (x.FirstName.Contains(model.UserId) || x.LastName.Contains(model.UserId))).ToList().ToPagedList(page ?? 1, 6);
                model = new UserAndMassiveManagementViewModel
                {
                    UserOfCompany = ListOfUser,
                    AreasOfTheCompany = GetArea(companyId),
                    CityOfTheCompany = GetCityOfTheCompany(),
                    LocationOfTheCompany = GetLocationOfTheCompany(companyId),
                    PositionTheCompany = GetPosition(companyId),
                    CompanyId=companyId
                };
                return View("ManagementUser", model);
            }
        }
        
        public IEnumerable<SelectListItem> GetArea(int CompanyId)
        {
            List<Area> AreaOfMyCompany = ApplicationDbContext.Areas.Where(x => x.Company.CompanyId == CompanyId).ToList();
            IEnumerable<SelectListItem> Areas = AreaOfMyCompany.Select(x =>
           new SelectListItem
           {
               Value = x.AreaId.ToString(),
               Text = x.AreaName
           });
            return new SelectList(Areas, "Value", "Text");
        }
        public IEnumerable<SelectListItem> GetPosition(int CompanyId)
        {
            List<Cargo> PositionTheCompany = ApplicationDbContext.Cargos.Where(x => x.Company.CompanyId == CompanyId).ToList();
            IEnumerable<SelectListItem> Positions = PositionTheCompany.Select(x =>
           new SelectListItem
           {
               Value = x.Posi_id.ToString(),
               Text = x.Posi_Description
           });
            return new SelectList(Positions, "Value", "Text");
        }
        public IEnumerable<SelectListItem> GetCityOfTheCompany()
        {
            List<Ciudad> CityOfTheCompany = ApplicationDbContext.Ciudades.ToList();
            IEnumerable<SelectListItem> Citys = CityOfTheCompany.Select(x =>
           new SelectListItem
           {
               Value = x.City_Id.ToString(),
               Text = x.City_Name
           });
            return new SelectList(Citys, "Value", "Text");
        }
        public IEnumerable<SelectListItem> GetLocationOfTheCompany(int CompanyId)
        {
            List<Ubicacion> LocationOfTheCompany = ApplicationDbContext.Ubicaciones.Where(x => x.Company.CompanyId == CompanyId).ToList();
            IEnumerable<SelectListItem> Locations = LocationOfTheCompany.Select(x =>
           new SelectListItem
           {
               Value = x.Loca_Id.ToString(),
               Text = x.Loca_Description
           });
            return new SelectList(Locations, "Value", "Text");
        }
        public ApplicationUser GetActualUserId()
        {
            var userId = User.Identity.GetUserId();
            var user = UserManager.FindById(userId);
            return user;
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateUser(UserAndMassiveManagementViewModel UserObtainedOfTheView)
        {
            if (ModelState.IsValid)

            {
                var company = ApplicationDbContext.Companies.Find(UserObtainedOfTheView.CompanyId);
                var ubi = ApplicationDbContext.Ubicaciones.Find(UserObtainedOfTheView.LocationId);
                ApplicationUser UserToCreate = new ApplicationUser
                {
                    UserName = UserObtainedOfTheView.UserName,
                    FirstName = UserObtainedOfTheView.FirstName,
                    LastName = UserObtainedOfTheView.LastName,
                    Email = UserObtainedOfTheView.Email,
                    Document = UserObtainedOfTheView.Document,
                    Role = (ROLES)UserObtainedOfTheView.Role,
                    AreaId = UserObtainedOfTheView.AreaId,
                    Company = company,
                    CompanyId=company.CompanyId,
                    CityId = UserObtainedOfTheView.CityId,
                    PositionId = UserObtainedOfTheView.PositionId,
                    LocationId = UserObtainedOfTheView.LocationId,                 
                    TermsandConditions = Terms_and_Conditions.No,
                    //Metodo creado para la asignación del dato tipo string al mensaje
                    Location_Desc = ubi.Loca_Description,
                };
                string next = VerifyUserFields(UserToCreate);

                if (next == "success")
                {
                    IdentityResult result = await UserManager.CreateAsync(UserToCreate, UserObtainedOfTheView.UserName);
                    if (result.Succeeded)
                    {
                        SendEmail(UserToCreate.FirstName + " " + UserToCreate.LastName, UserToCreate.Email, UserToCreate.UserName, UserToCreate.Company.CompanyName, UserToCreate.Location_Desc);
                        TempData["Menssage"] = "Usuario creado con éxito";
                       
                        return RedirectToAction("ManagementUser", new { id=UserToCreate.CompanyId});
                    }
                    TempData["Warning"] = result.Errors.First();
                }
                else
                {
                    string[] a = next.Split(';');
                    string error = a[0];
                    TempData["Menssage"] = " Error en la carga: descripcion. " + error + " favor verifica";
                    return RedirectToAction("ManagementUser", new { id = UserToCreate.CompanyId });
                }

            }
            return RedirectToAction("ManagementUser", new { id = UserObtainedOfTheView.CompanyId });
        }
        private string VerifyUserFields(ApplicationUser result)
        {
            

            List<Area> Areas = ApplicationDbContext.Areas.Where(x => x.CompanyId == result.CompanyId).ToList();
            List<Ciudad> Citys = ApplicationDbContext.Ciudades.ToList();
            List<Ubicacion> locations = ApplicationDbContext.Ubicaciones.Where(x => x.CompanyId == result.CompanyId).ToList();
            List<Cargo> positions = ApplicationDbContext.Cargos.Where(x => x.CompanyId == result.CompanyId).ToList();

            if (result.Email == null || result.Email.Length > 60)
            {
                return "no hay Email o excede el tamaño;";
            }

DemoScore/Views/UserAndMassiveManagement/Companies.cshtml
@using DemoScore.Models;
@using DemoScore.Models.ViewModel;


@model AdminGeneralViewModel

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


@*Script sections modal*@
@if (TempData["Menssage"] != null)
{
    <script type="text/JavaScript">
        $(document).ready(function () {
            $("#Menssages").modal();
        });
    </script>
}

<div class="jumbotron">
    <br /><br /><br /><br />
    <h1 class="title"> Compañias</h1>
    <br /><br />
    <br /><br />
    <!--muestra la lista de compañias-->
    <div class="col-md-12">
        @if (Model.ListCompanies.Count == 0)
        {
            <br />
            <br />
            <br />
                    <br />
                    <br />
                    <div class="row">
                        <center> <img src="@Url.Content("~/Content/Imagenes/1.jpg")" style="width:600px;" alt="Imagen responsive" class="img-responsive" /></center>
                    </div>
        }
        else
        {

            <hr style="width:100%; float:left; border:dashed; border-color: #A3DC68; border-width:thin;">
            <div class="table-responsive col-md-12 col-sm-12">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr class="success">
                            <th>  Nombre Compañia</th>
                            <th> Cantidad de usuarios</th>
                            <th>Ingresar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ListCompanies)
                        {
                            <tr>
                                <td>@item.CompanyName</td>
                                <td>@item.CompanyUser</td>
                                <td><a href="@Url.Action("ManagementUser", "UserAndMassiveManagement", new {id = @item.CompanyId})" class="btn btn-primary">Ingresar</a></td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        }
    </div>
</div>


<!-- this is message-->
<div id="Menssages" class="modal fade" role="dialog">
    <div class="modal-dialog1">
        <div class="modal-content">
            <div class="modal-body">
                <p>
                    @TempData["Menssage"]
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>







@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoScore/Views/UserAndMassiveManagement/MassiveRegister.cshtml
@using DemoScore.Models;
@using DemoScore.Models.ViewModel;
@using System.Data;
@model LogoUserMasive
@{
    ViewBag.Title = "MassiveRegister";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Menssage"] != null)
{
    @section Scripts {
        <script type="text/JavaScript">
            $(document).ready(function () {
                $("#Menssages").modal();
            });
        </script>
    }}
<br /><br /><br /><br /><br /><br />
<div class="row fecha">
    <div class="btn-group btn-breadcrumb">
        <a href="@Url.Action("Index", "Home")" class="btn btn-info"><i class="glyphicon glyphicon-home"></i></a>
        <a href="@Url.Action("ManagementUser", "UserAndMassiveManagement",new {id = Model.companyId})" class="btn btn-info">GESTIÓN DE USUARIOS</a>
    </div>
</div>
<div class="panel-primary">
    @using (Html.BeginForm("MassiveRegister", "UserAndMassiveManagement", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
    @Html.HiddenFor(x=>x.companyId)
        <h4>Registro Masivo de Usuarios</h4>
        <div class="fecha">
            <a href="~/Reports/CargaMasivaUsuarios.xlsx" target="_blank" download="CargaMasivaUsuarios.xlsx"><h1 style="color:red;">Descargar Formato</h1></a>
        </div>
            <br /><br />
            <div class="logo_inicial">
                <br />
                <div class='center-block' style='width:500px;height:200px;'>
                    <br />
                    <p><img class="img-responsive" src="~/Content/Imagenes/logo_inicial2.png" border="0" width="1280" height="1000" /></p>  
                </div>
                </div>
            <br /><br /><br /><br /><br />
            <br /><br /><br /><br /><br /><br />
            @Html.ValidationSummary("", new { @class = "text-danger" })
            <div class="form-group col-md-4">
                <label class="col-md-8">Selecciona el archivo Excel</label>
            </div>
            <div class="form-group col-md-12">
                <input type="file" name="excelUpload" class="col-md-7" />
            </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-8">
                        <input type="submit" value="Registrar Usuarios" class="btn btn-default" />
                    </div>
                </div>
    }

    <br />
    <div class="table-responsive">
        @if (Model.data != null)
        {
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        @foreach (DataColumn col in Model.data.Columns)
                        {
                            <th>@col.ColumnName</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (DataRow row in Model.data.Rows)
                {
                        <tr>
                            @foreach (DataColumn col in Model.data.Columns)
                            {
                                <td>@row[col.ColumnName]</td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

<!-- this is message-->
<div id="Menssages" class="modal fade" role="dialog">
    <div class="modal-dialog1">
        <div class="modal-content">
            <div class="modal-body">
                <p>
                    @TempData["Menssage"]
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>